### ISSUE TITLE
Ubuntu Focal Apache2 

### ISSUE THREAD

**Issue by mfones** [linux-pam/linux-pam#344] opened 2021-04-02 15:47 UTC
Command sudo sevice apahe2 restart failed. 
journactl -ex ...
pam_unix(sudo:auth): Couldn't open /etc/securetty: No such file or directory

**Comment by mfones** [comment] 2021-04-05 19:30
Turns out ngnx was running at the same time. Shutting down nginx allowed apache to run. So I believe the error message has no impact on running apache.

**Comment by t8m** [comment] 2021-04-06 06:27
Closing as this is not a bug in upstream Linux-PAM project.

**Closed by t8m** 2021-04-06 06:27 UTC
