### ISSUE TITLE
pam_unix/passverify.c does not allow empty passwords with non-empty hashes

### ISSUE THREAD

**Issue by severach** [linux-pam/linux-pam#758] opened 2024-01-29 18:59 UTC
I have a user with a password length of 0 crypt and set in /etc/shadow. The new code b3020da7da384d769f27a8713257fbe1001878be in `modules/pam_unix/passverify.c` does not allow this user to login.

The hash was generated with this code.

```
#!/usr/bin/perl

use strict;
use warnings;
use integer;
no overloading;

# 2021-06-13 PAM disabled 3DES MD5 and SHA256 passwords.
# The famous U6aMy0wojraho no longer works.
# Most password utilities will not generate a hash for a blank password and blank salt.
# This generates a high security SHA512 blank password for passwordless logons.
# -CJS

print crypt("", '$6$$'); # U6=3DES with well known salt, $1$$=MD5, $5$$=SHA256, $6$$=SHA512
```

This patch fixes the problem though it still isn't the same as the the code in 1.53.

```
diff -ru5 a/modules/pam_unix/passverify.c b/modules/pam_unix/passverify.c
--- a/modules/pam_unix/passverify.c 2024-01-17 05:29:36.000000000 -0500
+++ b/modules/pam_unix/passverify.c 2024-01-29 13:46:34.277941821 -0500
@@ -236,17 +236,17 @@
 #else
      /* we must run helper for NIS+ passwords */
      return PAM_UNIX_RUN_HELPER;
 #endif
    } else if (is_pwd_shadowed(*pwd)) {
-#ifdef HELPER_COMPILE
      /*
       * shadow password file entry for this user,
       * if shadowing is enabled
       */
      *spwdent = getspnam(name);
      if (*spwdent == NULL || (*spwdent)->sp_pwdp == NULL)
+#ifdef HELPER_COMPILE
        return PAM_AUTHINFO_UNAVAIL;
 #else
      /*
       * The helper has to be invoked to deal with
       * the shadow password file entry.
```

**Comment by ldv-alt** [comment] 2024-01-30 11:13
I don't see how it is related to #686.

**Comment by ldv-alt** [comment] 2024-02-14 16:09
I suppose the problem is elsewhere.

**Comment by severach** [comment] 2024-02-14 21:00
I don't know what the helper is but I suspect the problem is that the helper does not approve blank passwords. This code does approve blank passwords through a comedy of errors.

**Comment by ldv-alt** [comment] 2024-02-14 21:46
The helper behavior with regards to blank passwords is controlled by `nullok` option.  The same applied to `pam_unix` as a whole.

**Comment by severach** [comment] 2024-02-14 22:33
nullok is present but it stopped working with the new code.

**Comment by ldv-alt** [comment] 2024-02-14 22:50
Note that "the new code" is not new at all: the helper has been used for less privileged users for eons.

**Comment by ldv-alt** [comment] 2024-03-25 15:23
> @ldv-alt the label is wrong. This isn't a question but a serious bug that breaks login functionality.

Unfortunately, I have no means to verify your claim, but if it's correct, then pam_unix `nullok` didn't work with unprivileged users for a long time already.  The change you're talking about just makes pam_unix use the privileged helper unconditionally.

**Comment by ldv-alt** [comment] 2024-03-25 16:00
> As for "the change" I'm talking about. Personally I'm not talking about any particular change so much as PAM not functioning for passwordless logins.

Could you verify whether older pam_unix (from pam 1.5.3) in your setup allowed passwordless authentication in non-root processes (e.g. vlock and screensavers, if they aren't running as root), please?

**Comment by thkukuk** [comment] 2024-03-26 15:40
> Meanwhile downstream in the linked ticket Trofi bisected to a commit in pam:
> 
> > Bisected linux-pam down to [b3020da](https://github.com/linux-pam/linux-pam/commit/b3020da7da384d769f27a8713257fbe1001878be) pam_unix/passverify: always run the helper to obtain shadow password file entries.

As Dmitry wrote: if nullok is broken today, it was already broken before for unprivileged processes since a long time. The patch does nothing else than unifying the behavior of privileged and unprivileged processes.

**Comment by thkukuk** [comment] 2024-03-27 09:08
It seems there is some confusion here:
`nullok` is for **empty** password entries, not for password of **zero length**.
According to the first comment, this is about accounts with a valid password hash, which was generated with an empty input.
This works fine for me with Linux-PAM 1.6.0 on openSUSE and I cannot find any code which checks for zero length of the input.
@severach @TomMD are you sure that it works for you if you change the password to a longer one?

My impression is: NixOS installs the helper application wrong or blocks them with some security rules.
It is at least no generic problem, as I cannot reproduce it on openSUSE MicroOS and Tumbleweed.

**Comment by trofi** [comment] 2024-03-27 21:49
Is there an easy way to run `unix_chkpwd` from the tty in a way that it would check password and return the status? That might help debugging it locally quite a bit.

**Comment by trofi** [comment] 2024-03-27 22:13
linux-pam-1.6.0:

```
$ printf "\0" | unix_chkpwd nulloktest nullok; echo $?
9

$ printf "\0" | sudo unix_chkpwd nulloktest nullok; echo $?
7
```

Which is probably `#define PAM_AUTHINFO_UNAVAIL 9` and `#define PAM_AUTH_ERR 7`.

`nixos` does a bit unusual things to `unix_chkpwd` to wrap it into a `SUID` binary. It certainly works for unprivileged users with non-empty passwords. At least the permissions are not unexpected:

```
$ ls -l `which unix_chkpwd`
-r-s--x--x 1 root root 63472 Mar 27 22:03 /run/wrappers/bin/unix_chkpwd
```

Full `strace`:

<details>
<summary>
`$ printf "\0" | sudo strace -f unix_chkpwd nulloktest nullok; echo $?`
</summary>
execve("/run/wrappers/bin/unix_chkpwd", ["unix_chkpwd", "nulloktest", "nullok"], 0x7ffeeaf3e4f8 /* 35 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x40e2b8)       = 0
set_tid_address(0x40e3f0)               = 2674867
getxattr("/proc/self/exe", "security.capability", 0x7fff1b45ca40, 24) = -1 ENODATA (No data available)
execve("/nix/store/ma1pk2a0s8cklv1pgpjb54wwc70cg532-linux-pam-1.6.0/bin/unix_chkpwd", ["unix_chkpwd", "nulloktest", "nullok"], 0x7fff1b45cb18 /* 34 vars */) = 0
brk(NULL)                               = 0x562ee5cd7000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffe54dd0260) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f85d0be2000
access("/etc/ld-nix.so.preload", R_OK)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/glibc-hwcaps/x86-64-v3/libcrypt.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe54dcf490, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/glibc-hwcaps/x86-64-v2/libcrypt.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe54dcf490, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/libcrypt.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0555, st_size=115856, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 143904, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f85d0bbe000
mmap(0x7f85d0bc0000, 65536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f85d0bc0000
mmap(0x7f85d0bd0000, 32768, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x12000) = 0x7f85d0bd0000
mmap(0x7f85d0bd8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7f85d0bd8000
mmap(0x7f85d0bda000, 29216, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f85d0bda000
close(3)                                = 0
openat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/libaudit.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/glibc-hwcaps/x86-64-v3/libaudit.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe54dcf470, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/glibc-hwcaps/x86-64-v2/libaudit.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe54dcf470, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/libaudit.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0555, st_size=148872, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 205008, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f85d0b8b000
mmap(0x7f85d0b8f000, 32768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f85d0b8f000
mmap(0x7f85d0b97000, 86016, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc000) = 0x7f85d0b97000
mmap(0x7f85d0bac000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x20000) = 0x7f85d0bac000
mmap(0x7f85d0bae000, 61648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f85d0bae000
close(3)                                = 0
openat(AT_FDCWD, "/nix/store/kp31zcpazmiawg1n7xspnsp86x9rhmhf-libxcrypt-4.4.36/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/y9p605m57g0np393rmf2wpm7yjan0jnn-audit-3.1.2/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/glibc-hwcaps/x86-64-v3/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe54dcf450, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/glibc-hwcaps/x86-64-v2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe54dcf450, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\202\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0555, st_size=2265064, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2002320, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f85d09a2000
mmap(0x7f85d09c8000, 1421312, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f85d09c8000
mmap(0x7f85d0b23000, 348160, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x181000) = 0x7f85d0b23000
mmap(0x7f85d0b78000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d5000) = 0x7f85d0b78000
mmap(0x7f85d0b7e000, 52624, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f85d0b7e000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f85d09a0000
arch_prctl(ARCH_SET_FS, 0x7f85d09a0b80) = 0
set_tid_address(0x7f85d09a0e50)         = 2674867
set_robust_list(0x7f85d09a0e60, 24)     = 0
rseq(0x7f85d09a14a0, 0x20, 0, 0x53053053) = 0
mprotect(0x7f85d0b78000, 16384, PROT_READ) = 0
mprotect(0x7f85d0bac000, 4096, PROT_READ) = 0
mprotect(0x7f85d0bd8000, 4096, PROT_READ) = 0
mprotect(0x562ee594c000, 4096, PROT_READ) = 0
mprotect(0x7f85d0c1b000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
rt_sigaction(SIGILL, {sa_handler=0x562ee59491e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESETHAND|0xffffffff00000000, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=0x562ee59491e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESETHAND|0xffffffff00000000, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x562ee59491e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESETHAND|0xffffffff00000000, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x562ee59491e0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESETHAND|0xffffffff00000000, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f85d09dfeb0}, NULL, 8) = 0
ioctl(0, TCGETS, 0x7ffe54dcff80)        = -1 ENOTTY (Inappropriate ioctl for device)
getuid()                                = 0
read(0, "\0", 513)                      = 1
getrandom("\xf4\x72\x34\xcd\x41\xf6\xba\xb7", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x562ee5cd7000
brk(0x562ee5cf8000)                     = 0x562ee5cf8000
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
sendto(3, "\2\0\0\0\v\0\0\0\7\0\0\0passwd\0", 19, MSG_NOSIGNAL, NULL, 0) = 19
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="", iov_len=7}, {iov_base="", iov_len=8}], msg_iovlen=2, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 0
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
sendto(3, "\2\0\0\0\0\0\0\0\v\0\0\0nulloktest\0", 23, MSG_NOSIGNAL, NULL, 0) = 23
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
read(3, "\2\0\0\0\1\0\0\0\v\0\0\0\2\0\0\0\362\3\0\0d\0\0\0\1\0\0\0\21\0\0\0"..., 36) = 36
read(3, "nulloktest\0x\0\0/home/nulloktest\0/"..., 63) = 63
close(3)                                = 0
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0444, st_size=213, ...}, 0) = 0
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=130, ...}, 0) = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=213, ...}, AT_EMPTY_PATH) = 0
read(3, "passwd:    files systemd\ngroup: "..., 4096) = 213
read(3, "", 4096)                       = 0
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=213, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/shadow", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0640, st_size=3455, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "nixbld21:!:1::::::\nnixbld26:!:1:"..., 4096) = 3455
close(3)                                = 0
exit_group(7)                           = ?
+++ exited with 7 +++
7
</details>

**Comment by trofi** [comment] 2024-03-27 22:41
Adding a bit of `printf()` debugging shows that rejection happens around `hash == NULL`:

```c
int
helper_verify_password(const char *name, const char *p, int nullok)
{
        struct passwd *pwd = NULL;
        char *hash = NULL;
        int retval;

        retval = get_pwd_hash(name, &pwd, &hash);

        if (pwd == NULL || hash == NULL) { // <- here
                helper_log_err(LOG_NOTICE, "check pass; user unknown");
                retval = PAM_USER_UNKNOWN;
...
```

`get_pwd_hash()` fails at `get_account_info()`. `get_account_info()` fails at `*spwdent == NULL`:

```c
PAMH_ARG_DECL(int get_account_info,
        const char *name, struct passwd **pwd, struct spwd **spwdent)
{
...
                } else if (is_pwd_shadowed(*pwd)) {
#ifdef HELPER_COMPILE
                        /*
                         * shadow password file entry for this user,
                         * if shadowing is enabled
                         */
                        *spwdent = getspnam(name);
                        if (*spwdent == NULL || (*spwdent)->sp_pwdp == NULL)
                                return PAM_AUTHINFO_UNAVAIL;
```

Could it be that `nscd` does not return any `/etc/shadow` data and that requires extra configuration?

**Comment by trofi** [comment] 2024-03-28 06:56
If it helps example `/etc/shadow` entry generated by `nixos` for blank passwords is this one:

```
nulloktest:$6$Yy4ty2jJ$bsVQWo8qlXC6UHq1/qTC3UR60ZJKmKApJ3Wj7DreAy8FxlVKtlDnplFQ7jMLVlDqordE7e4t49GvTb.aI59TP0:1::::::
```

Note: it's distinct from an empty hash.

I think it's calculated by this perl code https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/nixos/modules/config/update-users-groups.pl#L37

```perl
sub hashPassword {
    my ($password) = @_;
    my $salt = "";
    my @chars = ('.', '/', 0..9, 'A'..'Z', 'a'..'z');
    $salt .= $chars[rand 64] for (1..8);
    return crypt($password, '$6$' . $salt . '$');
}
```

**Comment by trofi** [comment] 2024-03-28 07:31
The bug is in `modules/pam_unix/passverify.c` annotated with `// bug: here empty password implies empty hash in the database`: 

```c
int
helper_verify_password(const char *name, const char *p, int nullok)
{
        struct passwd *pwd = NULL;
        char *hash = NULL;
        int retval;

        retval = get_pwd_hash(name, &pwd, &hash);

        if (pwd == NULL || hash == NULL) {
                helper_log_err(LOG_NOTICE, "check pass; user unknown");
                retval = PAM_USER_UNKNOWN;
        } else if (p[0] == '\0' && nullok) {
                if (hash[0] == '\0') {
                        retval = PAM_SUCCESS;
                } else { // bug: here empty password implies empty hash in the database
                        retval = PAM_AUTH_ERR;
                }
        } else {
                retval = verify_pwd_hash(p, hash, nullok);
        }

        if (hash) {
                pam_overwrite_string(hash);
                _pam_drop(hash);
        }

        p = NULL;               /* no longer needed here */

        return retval;
}
```

The following workaround helps validating empty password with non-mepty hash (real fix should be less hacky):

```diff
--- a/modules/pam_unix/passverify.c
+++ b/modules/pam_unix/passverify.c
@@ -1112,7 +1112,7 @@ helper_verify_password(const char *name, const char *p, int nullok)
        if (pwd == NULL || hash == NULL) {
                helper_log_err(LOG_NOTICE, "check pass; user unknown");
                retval = PAM_USER_UNKNOWN;
-       } else if (p[0] == '\0' && nullok) {
+       } else if (p[0] == '\0' && nullok && 0) {
                if (hash[0] == '\0') {
                        retval = PAM_SUCCESS;
                } else {
```

**Comment by ldv-alt** [comment] 2024-03-28 09:43
Thanks! It seems to be a regression caused by #242 that was merged before v1.5.0 almost 4 years ago.

**Comment by trofi** [comment] 2024-03-28 22:21
My attempt at fixing it:
- https://github.com/linux-pam/linux-pam/pull/784

**Comment by ldv-alt** [comment] 2024-03-29 08:39
While the issue with allowing empty passwords with non-empty hashes is a regression, it's an old one.  Just for the record, could you clarify a bit, please, why it was triggered in `nixos` only now by the change to use the helper?

**Comment by trofi** [comment] 2024-03-29 09:37
The unexpected rejection of empty password with non-empty hash happens in `helper_verify_password()` function. AFAIU that function is only used in `unix_chkpwd` external helper. It the function was used in the non-helper case as well we would see the problem to pop up earlier in `nixos`.

Bisect says that https://github.com/linux-pam/linux-pam/commit/b3020da7da384d769f27a8713257fbe1001878be changed the behaviour of empty password with non-empty hash for login attempts via `tty` `login` binary (from `shadow` package). The primary use case for password-less users are one-off test minimal VMs. AFAIU the https://github.com/linux-pam/linux-pam/commit/b3020da7da384d769f27a8713257fbe1001878be change enabled helper usefor `login` binary and people started noticing that they can't create throwaway VMs with empty passwords as `helper_verify_password()` is now in effect.

Does it sound plausible?

**Comment by ldv-alt** [comment] 2024-03-29 10:49
As the name says, `helper_verify_password` is indeed used only by external helpers, and `_unix_verify_password` which is the only user of `verify_pwd_hash` besides `helper_verify_password` doesn't have this issue.

I'd say everything is settled now. Thanks for the analysis and the fix!

**Closed** 2024-03-29 10:51 UTC
Labels: bug

**Comment by severach** [comment] 2024-03-29 20:56
Works here with my blank salt password.

**Comment by trofi** [comment] 2024-07-23 18:58
I agree it's a bug. Not sure if there is a good workaround.

I've been meaning to look at that in detail and fix the regression. Will try this weekend.

**Comment by ldv-alt** [comment] 2024-10-09 20:34
> I cannot avoid to notice that while my empty password with non-empty hash previously returned a root user confirmation notice before 1.6.0 (be it with sudo or the polkit dialogs), now any call is automatically accepted. Is there a way to revert back to the previous behaviour?

As this seems to be a different issue, could you submit a separate bug, please?
