### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [linux-pam/linux-pam#165] opened 2020-01-03 12:28 UTC
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by t8m** [comment] 2020-02-28 09:54
-     [mandatory] which branch is your development branch?

**master** branch is the development branch.

-     [mandatory] have you merged latest translation from Zanata and locked the project?

I've locked it but I was not able to pull the latest translation because I could not make Zanata work for me.

-     [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

Same as source code dual license: **BSD-3-Clause OR GPL-2.0-or-later**

**Comment by Jibec** [comment] 2020-02-28 23:27
Project is created there: https://translate.fedoraproject.org/projects/linux-pam/

I looked at Zanata content, it looks obsolete to me. Many languages has minor content change and I'm not qualified enough to tell what to select. Communicating to translators would probably give far better result than trying to do it ourselves.

Weblate will open a PR each time a contributor finish a tanslations.
Weblate will update LINGUAS.
Weblate will squash commit per author.
Weblate will update every single po files when you update your pot file

TODO: I don't know how to set double licensing in weblate, I'll learn it and fix it in the future.

I deleted empty translation files as they are useless.
Could you please connect to the translation platform and give me your usename so you are admin?

**Comment by Jibec** [comment] 2020-03-01 10:48
Double license is now properly configured.

Last step is you to connect to the translation platform and providing your usename to make you admin of your project.

**Comment by t8m** [comment] 2020-03-03 07:59
My Fedora project user name is tmraz.
I think putting there only the more lenient license (which is GPLv2 compatible) is fine.

**Comment by Jibec** [comment] 2020-03-03 08:35
Le 2020-03-03 08:59, Tomáš Mráz a écrit :
> My Fedora project user name is tmraz.

Done, you are now admin. (I didn't realize you already were a user sorry 
;))

> I think putting there only the more lenient license (which is GPLv2
> compatible) is fine.

In doubt, I explicitly wrote both licenses.


For general purpose questions, use mailing list: 
trans@lists.fedoraproject.org
For specific administration requests, use: 
http://pagure.io/fedora-l10n/tickets

**Comment by t8m** [comment] 2020-03-06 07:54
Thank you very much. Everything should be set-up now.

**Closed by t8m** 2020-03-06 07:54 UTC

**Comment by ldv-alt** [comment] 2020-03-06 18:36
On Fri, Jan 03, 2020 at 04:28:15AM -0800, Jean-Baptiste wrote:
> * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

Our project currently does not have files containing trailing whitespace, but the latest PR from Weblate https://github.com/linux-pam/linux-pam/pull/181 introduces commits that add trailing whitespace.

Is there any way to avoid trailing whitespace in PRs from Weblate?

**Comment by Jibec** [comment] 2020-03-06 20:25
I can have a look with Weblate team.
But for my own knowledge, I would like to understand, what is the impact?

**Comment by ldv-alt** [comment] 2020-03-06 21:02
On Fri, Mar 06, 2020 at 12:25:13PM -0800, Jean-Baptiste wrote:
> I can have a look with Weblate team.
> But for my own knowledge, I would like to understand, what is the impact?

My git hooks that guard against trailing whitespace
stop these commits from being pushed.

**Comment by ldv-alt** [comment] 2020-03-18 11:29
On Fri, Mar 06, 2020 at 10:36:05AM -0800, Dmitry V. Levin wrote:
> On Fri, Jan 03, 2020 at 04:28:15AM -0800, Jean-Baptiste wrote:
> > * [optional] do you need us to activate any specific checks? (this is a setting per component [3])
> 
> Our project currently does not have files containing trailing whitespace, but the latest PR from Weblate https://github.com/linux-pam/linux-pam/pull/181 introduces commits that add trailing whitespace.
> 
> Is there any way to avoid trailing whitespace in PRs from Weblate?

Looks like trailing whitespace is introduced "only" by those commits
that contain actual translation updates.

Commits containing the following message are OK:

  Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

In fact, they are more than just OK because they also remove all trailing
whitespace introduced by translation updates.

Could you fix these commits with translation updates, please?

**Comment by Jibec** [comment] 2020-03-18 21:53
I reported your issue upstream.

Existing workarounds:

option a: you edit commits as you didalready
option b: you deactivate po updates in weblate and does it yourself

Consequence of option b is what is described here: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts

**Comment by ldv-alt** [comment] 2020-03-27 23:45
On Wed, Mar 18, 2020 at 02:53:32PM -0700, Jean-Baptiste wrote:
> I reported your issue upstream.
> 
> Existing workarounds:
> 
> option a: you edit commits as you didalready
> option b: you deactivate po updates in weblate and does it yourself
> 
> Consequence of option b is what is described here: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts

Apparently, it didn't work out because weblate insists on adding trailing whitespace, see
https://translate.fedoraproject.org/projects/linux-pam/master/#alerts

Also, I don't have wlc command.

**Comment by Jibec** [comment] 2020-03-28 13:49
Please discuss the subject there: https://github.com/WeblateOrg/weblate/issues/3608
You insisting to talk to me instead of weblate dev, creates an unvolontary pressure on me.

There is dozens of projects to migrate from Zanata (don't forget this isn't the only subject I wish to contribute on my sparetime), and dont understand how a whitespace can prevent you to merge a PR.

You don't have wlc? It's the first line of the documentation https://docs.weblate.org/en/latest/wlc.html
You created merge conflicts? Please read: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts

I'm available as jibec in #fedora-devel or #fedora-i18n (freenode) in hope a direct discussion can solve the situation.

**Comment by ldv-alt** [comment] 2020-03-28 20:40
On Sat, Mar 28, 2020 at 06:49:14AM -0700, Jean-Baptiste wrote:
> Please discuss the subject there: https://github.com/WeblateOrg/weblate/issues/3608
> You insisting to talk to me instead of weblate dev, creates an unvolontary pressure on me.

Apparently, there is nothing to talk with weblate dev about,
they've just closed the issue as a duplicate of a merged pull request.

> There is dozens of projects to migrate from Zanata (don't forget this isn't the only subject I wish to contribute on my sparetime), and dont understand how a whitespace can prevent you to merge a PR.

I've installed a github ci hook that prohibits push and pull requests with trailing whitespace:
https://github.com/linux-pam/linux-pam/commit/a5d47d59cad4b5c3d1858884536e05a8e684f04d

> You don't have wlc? It's the first line of the documentation https://docs.weblate.org/en/latest/wlc.html
> You created merge conflicts? Please read: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts

An attempt to lock translation failed with the following diagnostics:
```You do not have permission to perform this action.```

> I'm available as jibec in #fedora-devel or #fedora-i18n (freenode) in hope a direct discussion can solve the situation.

Thanks.

**Comment by t8m** [comment] 2020-03-30 09:56
> On Sat, Mar 28, 2020 at 06:49:14AM -0700, Jean-Baptiste wrote: Please discuss the subject there: > You don't have wlc? It's the first line of the documentation https://docs.weblate.org/en/latest/wlc.html You created merge conflicts? Please read: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts
> An attempt to lock translation failed with the following diagnostics: ```You do not have permission to perform this action.```

Dmitry, I've added you to the project as admin. So you should be able to do it now. I am sorry for not being involved in this more recently as I am too busy with other duties.

**Comment by ldv-alt** [comment] 2020-03-30 14:00
On Mon, Mar 30, 2020 at 02:56:35AM -0700, Tomáš Mráz wrote:
> > On Sat, Mar 28, 2020 at 06:49:14AM -0700, Jean-Baptiste wrote: Please discuss the subject there: > You don't have wlc? It's the first line of the documentation https://docs.weblate.org/en/latest/wlc.html You created merge conflicts? Please read: https://docs.weblate.org/en/latest/admin/continuous.html?#avoiding-merge-conflicts
> > An attempt to lock translation failed with the following diagnostics: ```You do not have permission to perform this action.```
> 
> Dmitry, I've added you to the project as admin. So you should be able to do it now. I am sorry for not being involved in this more recently as I am too busy with other duties.

OK, I've brought https://translate.fedoraproject.org/projects/linux-pam/master/ in sync with our master branch, let's see whether it's enough.

Thanks.
