### ISSUE TITLE
pam 1.6.0-3 breaks openvpn login

### ISSUE THREAD

**Issue by tomasmez** [linux-pam/linux-pam#747] opened 2024-01-19 17:17 UTC
Hello, i posted the following bug at the Archlinux bug tracking system, but it appears to be an upstream bug:
https://gitlab.archlinux.org/archlinux/packaging/packages/pam/-/issues/3#note_157561

Pasting the description here for consistency:

> sudo: reports wrong password
> 
> openvpn: the error in the openvpn-connect log is:
> 
> ⏎[Jan 19, 2024, 10:31:24] SSL Handshake: peer certificate: CN=emmet, 2048 bit RSA, cipher: TLS_AES_256_GCM_SHA384 TLSv1.3 Kx=any Au=any Enc=AESGCM(256) Mac=AEAD
> ⏎[Jan 19, 2024, 10:31:24] Session is ACTIVE ⏎[Jan 19, 2024, 10:31:24] EVENT: GET_CONFIG
> ⏎[Jan 19, 2024, 10:31:24] Sending PUSH_REQUEST to server...
> ⏎[Jan 19, 2024, 10:31:24] AUTH_FAILED
> ⏎[Jan 19, 2024, 10:31:24] EVENT: AUTH_FAILED
> ⏎[Jan 19, 2024, 10:31:24] EVENT: DISCONNECTED ⏎[Jan 19, 2024, 10:36:37]
> OpenVPN core 3.git::d3f8b18b win x86_64 64-bit built on Feb 7 2023 16:08:10
> 
> Downgrading fixed both issues

I did a git-bisect between v1.5.3 and v1.6.0 and found that b3020da7da384d769f27a8713257fbe1001878be  is the first offending commit.

As a side note: i have another install in which sudo was not affected (openvpn is not installed there).

Tomas

**Comment by tomasmez** [comment] 2024-01-19 17:57
did more testing. Openvpn is being started via a systemd service.

when exectuted as root. the problem is not present.

i suspect systemd restrictions in place affect how openvpn access pam.

could this be my problem?

**Comment by stoeckmann** [comment] 2024-01-23 23:04
Looking at the downstream bug report and later comments, `sudo` seems to be actually unaffected by these changes, but merely has an issue because `pam_faillock.so` properly works when it gets triggered by repeated failed authentication attempts by OpenVPN. Is this correct?

Also, just to get this right: If you revert back to right before https://github.com/linux-pam/linux-pam/commit/b3020da7da384d769f27a8713257fbe1001878be then OpenVPN works for you? And if you keep everything in 1.6.0 and just revert this one commit, it fails?

**Comment by tomasmez** [comment] 2024-01-23 23:15
Hello. sudo is unaffected. you are correct. Only when OpenVPN triggers pam_faillock.so I cannot use sudo.

Reverting b3020da on top of v1.6.0 makes OpenVPN work again.

**Comment by ldv-alt** [comment] 2024-01-24 07:42
> i suspect systemd restrictions in place affect how openvpn access pam.
> could this be my problem?

Yes, it definitely can be the cause of your problem.

**Comment by thkukuk** [comment] 2024-01-24 15:03
We see the same problem on openSUSE, too: several apps can suddenly no longer authenticate.
Reason: apparmor profiles don't allow access of /sbin/unix-cbkpwd. So a clear bug in the apoarmor profiles which needs to be fixed there.

**Comment by stoeckmann** [comment] 2024-01-24 17:45
I have reproduced the problem with a current Arch Linux installation. Actually two to test OpenVPN client and server setup.

### Setup

An important note here is that OpenVPN server must be configured to actually use PAM in its configuration file, like
```
plugin openvpn-plugin-auth-pam.so login
```

The client itself must send username and password, of course. A configuration would be something like
```
auth-user-pass passfile.txt
```
And the passfile.txt contains something like
```
user
password
```

And very important is the start through systemd with a configuration like this one (Arch Linux distributes it as `/usr/lib/systemd/system/openvpn-server@.service`):
```
User=openvpn
Group=network
AmbientCapabilities=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SETPCAP CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SETPCAP CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
```

### Analysis

As configured by systemd unit, the process runs without root privileges, i.e. is started as user `openvpn` with group `network`. The user is not a member of another group. What happens here though is that the `openvpn` binary is called with `CAP_DAC_OVERRIDE` capability which effectively means that any file on the system can be opened.

This in turn allowed Linux-PAM in version 1.5.3 to call `getspnam` and succeed even though the user is not root.

But in version 1.6.0 we always call `unix_chkpwd` which, since the user `nobody` calls it and tries to get the shadow entries for user `user` (as sent by the client), drops its privileges to `nobody` because argument and user name are not equal.

The program `unix_chkpwd` is a setuid binary on Arch Linux. We set our UID and GUID within the code to the UID and GID of `nobody` which effectively messes up the previously granted capabilities so much that we are unable to retrieve the shadow entries.

### Solution

From Linux-PAM perspective, we can always call `setuid(0)` before actually calling the `unix_chkpwd` binary. If the program runs without root privileges AND without elevated capabilities, the setuid(0) call fails and we continue (debug log might be useful, of course).

Right now we only try to call `setuid(0)` if `geteuid()` returns 0: https://github.com/linux-pam/linux-pam/blob/9f19e7da7a014e022cdbba06accca171adef27e0/modules/pam_unix/support.c#L565-L572

If we always call `setuid(0)` and continue even if it fails, then the problem is solved.

From Arch Linux perspective, I'm not really that happy with the systemd unit configuration. It DOES work for situations if PAM is not involved, but these granted capabilities are A LOT. In my test setup, it looked reasonably okay to just configure the OpenVPN server to drop its privileges after authentication was performed, i.e. let OpenVPN do its thing. This involves User=root and no capabilities. Pretty much the previously stated 4 lines commented out.

Instead, in server configuration, I've added these two lines:
```
user nobody
group nobody
```

### Summary

Custom configuration of an OpenVPN installation on Arch Linux broke because capabilities have not been taken into account in `pam_unix.so`.

Can be fixed by user, downstream, or upstream.

**Comment by stoeckmann** [comment] 2024-01-24 19:20
> Is this expected?

Yes, it is. OpenVPN drops privileges after the connection is established. This `nobody` process is the child process. If you create a new connection, the `root` (parent) process performs the authentication and then spawns another process which drops to `nobody` as well.

I had a chat with an Arch developer and since I'm writing about OpenVPN again at this point: I guess it makes more sense to drop privileges to user `openvpn` and group `network` just to not have more processes running with `nobody` privileges.

But I also avoid giving too much OpenVPN-specific configuration recommendations. For one reason: I'm not an OpenVPN expert. And second: It's the Linux-PAM issue tracker here. ;)

**Comment by stoeckmann** [comment] 2024-01-24 19:22
> As per your comment, ive left my openvpn configuration as suggested.

Feel free to check out the linked PR and try to run with these changes. It should also work with your original configuration.

Feedback will help to evaluate if the fix helps you as well.

**Comment by tomasmez** [comment] 2024-01-24 19:41
> > As per your comment, ive left my openvpn configuration as suggested.
> 
> Feel free to check out the linked PR and try to run with these changes. It should also work with your original configuration.
> 
> Feedback will help to evaluate if the fix helps you as well.

Tested with the proposed patch and it fixes the problem with the standard openvpn unit file shipped with archlinux

Thanks for your support.

**Closed** 2024-01-30 21:57 UTC

**Comment by riku76** [comment] 2024-02-05 06:36
Are you going to release a fix for this soon? This breaks our software too. We are using AmbientCapabilities=CAP_DAC_READ_SEARCH for our systemd managed service to allow using authentication for a limited user and had to put upgrade of pam to hold due to this issue.
